# Generated by Django 2.1.2 on 2018-11-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category1_discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category2_discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stars', models.IntegerField()),
                ('Validity_of_this_rate', models.IntegerField()),
                ('Rate_explanation', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='Registration_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheapiesgr.Registration'),
        ),
        migrations.AddField(
            model_name='rating',
            name='Volunteer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheapiesgr.Volunteer'),
        ),
        migrations.AddField(
            model_name='category1',
            name='Category2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheapiesgr.Category2'),
        ),
        migrations.AddField(
            model_name='category',
            name='Category1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheapiesgr.Category1'),
        ),
    ]
