# Generated by Django 2.1.3 on 2018-11-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheapiesgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'answer', 'verbose_name_plural': 'answers'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categorys'},
        ),
        migrations.AlterModelOptions(
            name='category1',
            options={'verbose_name': 'category1', 'verbose_name_plural': 'category1s'},
        ),
        migrations.AlterModelOptions(
            name='category2',
            options={'verbose_name': 'category2', 'verbose_name_plural': 'category2s'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'rating', 'verbose_name_plural': 'ratings'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'registration', 'verbose_name_plural': 'registrations'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'volunteer', 'verbose_name_plural': 'volunteers'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=2000, verbose_name='answer_text'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.CharField(max_length=200, verbose_name='category_description'),
        ),
        migrations.AlterField(
            model_name='category1',
            name='category1_description',
            field=models.CharField(max_length=200, verbose_name='category1_description'),
        ),
        migrations.AlterField(
            model_name='category2',
            name='category2_description',
            field=models.CharField(max_length=200, verbose_name='category2_description'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='staff'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=2000, verbose_name='question_text'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate_explanation',
            field=models.CharField(max_length=1000, verbose_name='rate_explanation'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(verbose_name='stars'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='validity_of_this_rate',
            field=models.IntegerField(verbose_name='validity_of_this_rate'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='product_description',
            field=models.CharField(max_length=200, verbose_name='product_discription'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last_name'),
        ),
    ]
