# Generated by Django 2.1.3 on 2018-11-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheapiesgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Volunteer', 'verbose_name_plural': 'Volunteers'},
        ),
    ]
