# Generated by Django 2.1.3 on 2018-11-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheapiesgr', '0002_auto_20181126_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
