# Generated by Django 2.1.3 on 2018-11-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheapiesgr', '0003_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='name',
        ),
    ]
